[test]
preload = ["./test-preload.ts"]
coverageDir = "./test-results/coverage"
coverageThreshold = { lines = 0.8, functions = 0.8, statements = 0.8 }
coverageReporter = ["text", "lcov"]
coverageIgnoreSourcemaps = true
coveragePathIgnorePatterns = [
  "**/dist/**",
  "**/node_modules/**"
]
