packages:
  - packages/*
catalogs:
  lint:
    "@eslint/js": ^9.22.0
    eslint: ^9.22.0
    eslint-config-prettier: ^10.1.2
    eslint-plugin-prettier: ^5.2.6
    globals: ^16.0.0
    prettier: ^3.5.3
    typescript-eslint: ^8.31.1
  ts:
    tslib: ^2.8.1
    typescript: ^5.8.2
  vitest:
    "@vitest/coverage-v8": ^3.1.2
    "@vitest/ui": ^3.1.2
    happy-dom: ^17.4.6
    vitest: ^3.1.2
