packages:
  - packages/*
catalogs:
  lint:
    "@eslint/js": ^9.19.0
    eslint: ^9.19.0
    eslint-config-prettier: ^10.0.1
    eslint-plugin-prettier: ^5.2.3
    globals: ^15.14.0
    prettier: ^3.4.2
    typescript-eslint: ^8.21.0
  ts:
    tslib: ^2.8.1
    typescript: ^5.7.3
  vitest:
    "@vitest/coverage-v8": ^3.0.4
    happy-dom: ^16.7.2
    vitest: ^3.0.4
