packages:
  - packages/*
catalogs:
  lint:
    "@eslint/js": ^9.21.0
    eslint: ^9.21.0
    eslint-config-prettier: ^10.0.2
    eslint-plugin-prettier: ^5.2.3
    globals: ^16.0.0
    prettier: ^3.5.3
    typescript-eslint: ^8.26.0
  ts:
    tslib: ^2.8.1
    typescript: ^5.8.2
  vitest:
    "@vitest/coverage-v8": ^3.0.8
    "@vitest/ui": ^3.0.8
    happy-dom: ^17.2.2
    vitest: ^3.0.8
